title: FINA367 - Fixed-Income Investment - Spring 2020
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table"]
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
  - syllabus.md
  - financial_calculator.md
  - credit_risk.md
  - call_put_option.md
  - test.md
